# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# This creates an .xcworkspace file for your app
# use this file for future development on app
# include analytics by default
pod 'Firebase/Core'
pod 'Firebase/Messaging'
# pod 'react-native-fetch-blob',
#     :path => '../node_modules/react-native-fetch-blob'
# https://firebase.google.com/docs/ios/setup#available_pods


target ‘Saga’ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestIgniteApp

  # target 'TestIgniteAppTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
